version: 2
jobs:
  build:
    working_directory: ~/mnozenie
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install
      - save_cache:
      paths:
          - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test
      - run: sudo apt-get update && sudo apt-get install -y python-dev
      - run: sudo curl -O https://bootstrap.pypa.io/get-pip.py
      - run: sudo python get-pip.py
      - run: sudo pip install awscli --upgrade
      - run: aws --version
      - run: aws s3 ls
      - run: npm run deploy